### ISSUE TITLE
Exe says it's compiled using an unlicensed compiler

### ISSUE THREAD

**Issue by ThePizzaMuncher** [AleanaA/Easy-RPC#1]
When I try to open the program, it shows the following error message.

![image](https://user-images.githubusercontent.com/60735922/94439156-535e0d80-01a0-11eb-835b-905859cf8ad4.png)

After this, it quits.

**Comment by AleanaA** [comment]
This is an unfortunate byproduct of what i used to compile it
I'm not really maintaining this, but you can work around the issue by running `run.exe` in the `run` folder

**Comment by ThePizzaMuncher** [comment]
Thanks for coming back on this. I'll try your advice.
